### ISSUE TITLE
What model of battery?

### ISSUE THREAD

**Issue by leopd** [madelinegannon/jetson-nano-accessories#1]
What make/model of battery are these designs sized for?

**Comment by madelinegannon** [comment]
I'm using this INIU 5V/3A, 10,000mAh battery pack that's spec'ed in NVIDIA's Jetbot [BOM](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/bill-of-materials)

**Comment by leopd** [comment]
Thanks!
