### ISSUE TITLE
Utility belt for Xavier NX

### ISSUE THREAD

**Issue by mpottinger** [madelinegannon/jetson-nano-accessories#4]
Hello, just curious, would these designs work as well for the Xavier NX? It is the same form factor as the Jetson Nano, but more powerful. Specifically the Utility belt.

**Comment by madelinegannon** [comment]
Basically, but there would need to be slight modifications ... the board for the Nano and Xavier NX are the same. However, the XNX sits in a plastic case that holds its wifi antennae. This clips would just need to be modified a bit to receive the XNX's thicker plastic case.

In terms of power, I'm not sure if the battery pack is sufficient — _maybe_ in 10W mode??

**Comment by mpottinger** [comment]
Ok thank you. Yes powering even the nano has been a pain for me, the micro usb doesn't supply enough power for heavy usage.

**Comment by madelinegannon** [comment]
If you find better battery options, please share them with us!
